production:
  access_key_id: AKIAJDCB2QENJFUJZUAA
  secret_access_key: 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
  bucket: nm-gallery
  
  
development:
  access_key_id: AKIAJDCB2QENJFUJZUAA
  secret_access_key: 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
  bucket: nm-gallery